name: foodex
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.1
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.0.9
  google_fonts: ^6.2.1
  http: ^1.2.1
  shared_preferences: ^2.0.6
  workmanager: 0.5.2
  flutter_confetti: ^0.3.0
  path_provider: ^2.0.10 # Check for the latest version on pub.dev
  url_launcher: ^6.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
  adaptive_icon_foreground: "assets/images/logo1.png"
  adaptive_icon_background: #FFFFFF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
